CREATE TABLE sensor_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_type VARCHAR2(50),
    temperature NUMBER,
    soil_moisture NUMBER,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    irrigation_needed VARCHAR2(20)
);

SELECT * FROM sensor_data;

COMMIT;