CREATE TABLE sensor_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_type VARCHAR2(50),
    temperature NUMBER,
    soil_moisture NUMBER,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    irrigation_needed VARCHAR2(20)
);

INSERT INTO sensor_data (crop_type, temperature, soil_moisture, irrigation_needed)
VALUES ('Wheat', 22, 30, 'Yes');

INSERT INTO sensor_data (crop_type, temperature, soil_moisture, irrigation_needed)
VALUES ('rice', 25, 40, 'No');

INSERT INTO sensor_data (crop_type, temperature, soil_moisture, irrigation_needed)
VALUES ('corn', 30, 20, 'Yes');



SELECT * FROM sensor_data;